
FROM node:20-alpine AS builder
 
WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /

COPY --from=builder /app ./

RUN npm install -g next

EXPOSE 3000

CMD ["npm", "run", "start"]