spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikitaatikin519@gmail.com
    password: uybtqsganwbfpsrw
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 50000
          timeout: 30000
          writetimeout: 50000
    test-connection: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SPRING_EUREKA_DEFAULT_ZONE:localhost}:8761/eureka/

server:
  port: 8007

logging:
  level:
    web: debug
