spring:
  application:
    name: analytics-service

  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  mvc:
    format:
      date-time: iso
      time: iso
      date: iso

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${SPRING_EUREKA_DEFAULT_ZONE:localhost}:8761/eureka/

server:
  port: 8006

logging:
  level:
    web: debug
    sql: debug
debug: true


springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true