spring:
  application:
    name: api-gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user-service/**
          filters:
            - JwtAuthenticationFilter
            - StripPrefix=2
      discovery:
        locator:
          enabled: false
  codec:
    log-request-details: false


logging:
  level:
#    org.springframework.cloud.gateway: DEBUG
#    reactor.netty.http.client: DEBUG
#    root: debug
    web: debug

server:
  port: 8001
eureka:
  client:
    register-with-eureka: true
#    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
